package com.ltfs.cdp.offer.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Entity representing the historical changes in an offer's status.
 * This table tracks every status transition for an offer, providing an audit trail.
 */
@Entity
@Table(name = "offer_status_history")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class OfferStatusHistory {

    /**
     * Unique identifier for the offer status history record.
     * This is the primary key and is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * The unique identifier of the offer to which this status history record belongs.
     * This acts as a foreign key linking to the main Offer entity.
     */
    @Column(name = "offer_id", nullable = false, length = 50)
    private String offerId;

    /**
     * The status of the offer before the change occurred.
     * This field stores the previous state of the offer.
     */
    @Column(name = "old_status", nullable = false, length = 50)
    private String oldStatus;

    /**
     * The new status of the offer after the change.
     * This field stores the current state of the offer after the transition.
     */
    @Column(name = "new_status", nullable = false, length = 50)
    private String newStatus;

    /**
     * The timestamp when the status change occurred.
     * This records the exact date and time of the status transition.
     */
    @Column(name = "change_timestamp", nullable = false)
    private LocalDateTime changeTimestamp;

    /**
     * The identifier of the user or system component that initiated the status change.
     * This provides an audit trail of who or what caused the status update.
     */
    @Column(name = "changed_by", nullable = false, length = 100)
    private String changedBy;

    /**
     * Optional field for any additional remarks or reasons for the status change.
     * Can be used to store context or notes related to the status transition.
     */
    @Column(name = "remarks", length = 500)
    private String remarks;
}