# Stripe Configuration
# Purpose: Data exchange
# Type: payment
# Generated by Integration Generator Agent (default template)

# Example .env configuration

STRIPE_API_KEY=your_api_key_here
STRIPE_URL=https://api.example.com/v1
STRIPE_TIMEOUT=30
STRIPE_MAX_RETRIES=3
STRIPE_RETRY_DELAY=1
STRIPE_RATE_LIMIT_REQUESTS=100
STRIPE_RATE_LIMIT_PERIOD=60
STRIPE_LOG_LEVEL=INFO
STRIPE_CACHE_ENABLED=true
STRIPE_CACHE_TTL=300
