# Twilio Configuration
# Purpose: Data exchange
# Type: sms
# Generated by Integration Generator Agent (default template)

# Example .env configuration

TWILIO_API_KEY=your_api_key_here
TWILIO_URL=https://api.example.com/v1
TWILIO_TIMEOUT=30
TWILIO_MAX_RETRIES=3
TWILIO_RETRY_DELAY=1
TWILIO_RATE_LIMIT_REQUESTS=100
TWILIO_RATE_LIMIT_PERIOD=60
TWILIO_LOG_LEVEL=INFO
TWILIO_CACHE_ENABLED=true
TWILIO_CACHE_TTL=300
