version: "3.9"
services:
  backend:
    build: ./src/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./src/frontend
    ports:
      - "3000:80"
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase