from datetime import datetime, date
from typing import List, Optional, Dict, Any
from uuid import UUID

from pydantic import BaseModel, Field


# Base Schemas - common fields for input/output validation
class CustomerBase(BaseModel):
    mobile_number: Optional[str] = Field(None, max_length=20)
    pan_number: Optional[str] = Field(None, max_length=10)
    aadhaar_ref_number: Optional[str] = Field(None, max_length=12)
    ucid_number: Optional[str] = Field(None, max_length=50)
    previous_loan_app_number: Optional[str] = Field(None, max_length=50)
    customer_attributes: Optional[Dict[str, Any]] = Field(default_factory=dict)
    customer_segments: Optional[List[str]] = Field(default_factory=list)
    propensity_flag: Optional[str] = Field(None, max_length=50)
    dnd_status: bool = False


class OfferBase(BaseModel):
    offer_type: str = Field(..., max_length=50)
    offer_status: str = Field(..., max_length=50)
    product_type: str = Field(..., max_length=50)
    offer_details: Dict[str, Any] = Field(default_factory=dict)
    offer_start_date: Optional[date] = None
    offer_end_date: Optional[date] = None
    is_journey_started: bool = False
    loan_application_id: Optional[str] = Field(None, max_length=50)


class OfferHistoryBase(BaseModel):
    old_offer_status: str = Field(..., max_length=50)
    new_offer_status: str = Field(..., max_length=50)
    change_reason: Optional[str] = None
    snapshot_offer_details: Dict[str, Any] = Field(default_factory=dict)


class CampaignEventBase(BaseModel):
    event_source: str = Field(..., max_length=50)
    event_type: str = Field(..., max_length=100)
    event_details: Dict[str, Any] = Field(default_factory=dict)


# Create Schemas - for incoming request bodies (POST/PUT)
# These typically omit fields that are auto-generated by the database (e.g., IDs, timestamps)
class CustomerCreate(CustomerBase):
    pass


class OfferCreate(OfferBase):
    customer_id: UUID  # Required when creating an offer


class OfferHistoryCreate(OfferHistoryBase):
    offer_id: UUID
    customer_id: UUID


class CampaignEventCreate(CampaignEventBase):
    customer_id: UUID
    offer_id: Optional[UUID] = None  # Can be null if not tied to a specific offer


# Response Schemas - for outgoing response bodies (GET)
# These include all fields, including auto-generated ones, and are compatible with ORM objects
class Customer(CustomerBase):
    customer_id: UUID
    created_at: datetime
    updated_at: datetime

    class Config:
        orm_mode = True  # Enable ORM mode for SQLAlchemy compatibility


class Offer(OfferBase):
    offer_id: UUID
    customer_id: UUID
    created_at: datetime
    updated_at: datetime

    class Config:
        orm_mode = True


class OfferHistory(OfferHistoryBase):
    history_id: UUID
    offer_id: UUID
    customer_id: UUID
    change_timestamp: datetime

    class Config:
        orm_mode = True


class CampaignEvent(CampaignEventBase):
    event_id: UUID
    customer_id: UUID
    offer_id: Optional[UUID] = None
    event_timestamp: datetime

    class Config:
        orm_mode = True


# Schemas for specific API endpoint request/response bodies as per system design
class LeadCreateRequest(BaseModel):
    mobile_number: str = Field(..., max_length=20)
    pan_number: Optional[str] = Field(None, max_length=10)
    aadhaar_ref_number: Optional[str] = Field(None, max_length=12)
    loan_product: str = Field(..., max_length=50)
    offer_details: Dict[str, Any] = Field(default_factory=dict)


class LeadCreateResponse(BaseModel):
    status: str
    message: str
    customer_id: UUID


class DailyTallyReport(BaseModel):
    report_date: date
    total_customers: int
    active_offers: int
    new_leads_today: int
    conversions_today: int


class CustomerProfile(BaseModel):
    customer_id: UUID
    mobile_number: Optional[str]
    pan_number: Optional[str]
    current_offer: Optional[Offer] = None  # Embed the Offer schema for current offer details
    offer_history_summary: List[OfferHistory] = Field(default_factory=list)  # List of historical offers
    journey_status: Optional[str] = None  # Derived status from campaign_events or offers
    segments: List[str] = Field(default_factory=list)

    class Config:
        orm_mode = True