<template>
  <div class="dashboard-container">
    <h1>CDP Data Export Dashboard</h1>

    <p class="description">
      Use the buttons below to download various data files generated by the CDP system.
    </p>

    <div class="download-section">
      <button
        @click="downloadMoengageFile"
        :disabled="loadingStates.moengage"
        class="download-button"
      >
        <span v-if="loadingStates.moengage" class="spinner"></span>
        <span v-else>Download Moengage Campaign File (CSV)</span>
      </button>

      <button
        @click="downloadDuplicateFile"
        :disabled="loadingStates.duplicate"
        class="download-button"
      >
        <span v-if="loadingStates.duplicate" class="spinner"></span>
        <span v-else>Download Duplicate Customer Data (CSV)</span>
      </button>

      <button
        @click="downloadUniqueFile"
        :disabled="loadingStates.unique"
        class="download-button"
      >
        <span v-if="loadingStates.unique" class="spinner"></span>
        <span v-else>Download Unique Customer Data (CSV)</span>
      </button>

      <button
        @click="downloadErrorFile"
        :disabled="loadingStates.errors"
        class="download-button"
      >
        <span v-if="loadingStates.errors" class="spinner"></span>
        <span v-else>Download Data Upload Error File (Excel)</span>
      </button>
    </div>

    <div v-if="message" :class="['message', messageType]">
      {{ message }}
    </div>
  </div>
</template>

<script>
import axios from 'axios';

const API_BASE_URL = 'http://localhost:5000'; // Adjust if your Flask backend runs on a different port/host

export default {
  name: 'Dashboard',
  data() {
    return {
      loadingStates: {
        moengage: false,
        duplicate: false,
        unique: false,
        errors: false,
      },
      message: '',
      messageType: '', // 'success' or 'error'
      messageTimeout: null,
    };
  },
  methods: {
    async downloadFile(endpoint, filename, fileType, loadingKey) {
      this.loadingStates[loadingKey] = true;
      this.clearMessage();

      try {
        const response = await axios.get(`${API_BASE_URL}${endpoint}`, {
          responseType: 'blob', // Important for file downloads
        });

        const url = window.URL.createObjectURL(new Blob([response.data], { type: fileType }));
        const link = document.createElement('a');
        link.href = url;
        link.setAttribute('download', filename);
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);

        this.setMessage(`Successfully downloaded ${filename}`, 'success');
      } catch (error) {
        console.error(`Error downloading ${filename}:`, error);
        let errorMessage = `Failed to download ${filename}.`;
        if (error.response && error.response.data) {
          try {
            // Attempt to parse error message from blob if available
            const errorBlob = new Blob([error.response.data], { type: 'application/json' });
            const reader = new FileReader();
            reader.onload = () => {
              try {
                const errorJson = JSON.parse(reader.result);
                if (errorJson.message) {
                  errorMessage += ` Reason: ${errorJson.message}`;
                }
              } catch (e) {
                // Not a JSON error, use generic message
              }
            };
            reader.readAsText(errorBlob);
          } catch (e) {
            // Fallback to generic message
          }
        }
        this.setMessage(errorMessage, 'error');
      } finally {
        this.loadingStates[loadingKey] = false;
        this.setClearMessageTimeout();
      }
    },
    downloadMoengageFile() {
      this.downloadFile(
        '/exports/moengage-campaign-file',
        'moengage_campaign_data.csv',
        'text/csv',
        'moengage'
      );
    },
    downloadDuplicateFile() {
      this.downloadFile(
        '/exports/duplicate-customers',
        'duplicate_customer_data.csv',
        'text/csv',
        'duplicate'
      );
    },
    downloadUniqueFile() {
      this.downloadFile(
        '/exports/unique-customers',
        'unique_customer_data.csv',
        'text/csv',
        'unique'
      );
    },
    downloadErrorFile() {
      this.downloadFile(
        '/exports/data-errors',
        'data_upload_errors.xlsx',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'errors'
      );
    },
    setMessage(msg, type) {
      this.message = msg;
      this.messageType = type;
    },
    clearMessage() {
      clearTimeout(this.messageTimeout);
      this.message = '';
      this.messageType = '';
    },
    setClearMessageTimeout() {
      this.messageTimeout = setTimeout(() => {
        this.clearMessage();
      }, 5000); // Clear message after 5 seconds
    },
  },
  beforeUnmount() {
    clearTimeout(this.messageTimeout);
  },
};
</script>

<style scoped>
.dashboard-container {
  max-width: 800px;
  margin: 50px auto;
  padding: 30px;
  background-color: #f9f9f9;
  border-radius: 8px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  text-align: center;
}

h1 {
  color: #333;
  margin-bottom: 20px;
  font-size: 2.2em;
}

.description {
  color: #555;
  margin-bottom: 30px;
  line-height: 1.6;
  font-size: 1.1em;
}

.download-section {
  display: flex;
  flex-direction: column;
  gap: 15px;
  margin-bottom: 30px;
}

.download-button {
  background-color: #007bff;
  color: white;
  padding: 15px 25px;
  border: none;
  border-radius: 5px;
  font-size: 1.1em;
  cursor: pointer;
  transition: background-color 0.3s ease, transform 0.2s ease;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
}

.download-button:hover:not(:disabled) {
  background-color: #0056b3;
  transform: translateY(-2px);
}

.download-button:disabled {
  background-color: #cccccc;
  cursor: not-allowed;
}

.spinner {
  border: 4px solid rgba(255, 255, 255, 0.3);
  border-top: 4px solid #fff;
  border-radius: 50%;
  width: 20px;
  height: 20px;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.message {
  padding: 15px;
  border-radius: 5px;
  margin-top: 20px;
  font-weight: bold;
  font-size: 1em;
}

.message.success {
  background-color: #d4edda;
  color: #155724;
  border: 1px solid #c3e6cb;
}

.message.error {
  background-color: #f8d7da;
  color: #721c24;
  border: 1px solid #f5c6cb;
}
</style>