# Stripe Example Usage
    # Purpose: Data exchange
    # Type: payment
    # Generated by Integration Generator Agent (default template)

    from integrations.adapters.stripe_adapter import StripeAdapter

    def demonstrate_stripe_integration():
        """
        Demonstrate Stripe integration usage.
        """
        adapter = StripeAdapter()
        
        # Example: Get a resource
        resource_id = "example-resource-id"
        print(f"Fetching resource {resource_id} from Stripe...")
        result = adapter.get_resource(resource_id)
        
        if result["success"]:
            print(f"Successfully fetched resource: {result['data']['name']}")
        else:
            print(f"Failed to fetch resource: {result['error']}")
        
        # Example: Create a resource
        new_resource = {
            "name": "Example Resource",
            "description": "This is an example resource created via the Stripe adapter"
        }
        
        print(f"Creating new resource in Stripe...")
        create_result = adapter.create_resource(new_resource)
        
        if create_result["success"]:
            print(f"Successfully created resource: {create_result['data']['id']}")
        else:
            print(f"Failed to create resource: {create_result['error']}")

    if __name__ == "__main__":
        demonstrate_stripe_integration()
    